"""Add WordExclusion model

Revision ID: x56rn24y9zwi
Revises: h7i8j9k0l1m2
Create Date: 2025-01-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'x56rn24y9zwi'
down_revision = 'h7i8j9k0l1m2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_exclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynamic_id', sa.Integer(), nullable=False),
    sa.Column('usuarie_id', sa.Integer(), nullable=False),
    sa.Column('palavra', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dynamic_id'], ['dynamic.id'], ),
    sa.ForeignKeyConstraint(['usuarie_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_exclusion_created_at'), 'word_exclusion', ['created_at'], unique=False)
    op.create_index(op.f('ix_word_exclusion_dynamic_id'), 'word_exclusion', ['dynamic_id'], unique=False)
    op.create_index(op.f('ix_word_exclusion_usuario_id'), 'word_exclusion', ['usuarie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_exclusion_usuario_id'), table_name='word_exclusion')
    op.drop_index(op.f('ix_word_exclusion_dynamic_id'), table_name='word_exclusion')
    op.drop_index(op.f('ix_word_exclusion_created_at'), table_name='word_exclusion')
    op.drop_table('word_exclusion')
    # ### end Alembic commands ###
